# Generated by Django 5.0.2 on 2024-02-28 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='db_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_Product_ID', models.CharField(max_length=100)),
                ('db_Product_Name', models.TextField(max_length=255)),
                ('db_Product_Type', models.TextField(max_length=255)),
                ('db_Product_Category', models.TextField(max_length=255)),
                ('db_Product_Price', models.IntegerField()),
                ('db_Product_status', models.TextField(max_length=255)),
                ('db_Product_Brand', models.TextField(max_length=255)),
                ('db_Product_Size', models.TextField(max_length=255)),
                ('db_Product_Freshnes', models.TextField(max_length=255)),
                ('db_Product_MadeByCountry', models.TextField(max_length=255)),
                ('db_Product_Condition', models.TextField(max_length=255)),
                ('db_Product_Description', models.TextField(max_length=255)),
                ('db_Product_QR_Code', models.TextField(max_length=255)),
                ('db_Product_IssueDate', models.DateField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
