# Generated by Django 4.2.7 on 2024-02-29 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreCommerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='db_Accessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_Access_ID', models.CharField(max_length=100)),
                ('db_Access_UseFor', models.TextField(max_length=255)),
                ('db_Access_Category', models.TextField(max_length=255)),
                ('db_Access_GenderBase', models.TextField(max_length=255)),
                ('db_Access_AgeBase', models.TextField(max_length=255)),
                ('db_Access_Color', models.TextField(max_length=255)),
                ('db_Access_Extra', models.TextField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='db_Cloth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_Cloth_ID', models.CharField(max_length=100)),
                ('db_Cloth_Color', models.TextField(max_length=255)),
                ('db_Cloth_GenderBase', models.TextField(max_length=255)),
                ('db_Cloth_AgeBase', models.TextField(max_length=255)),
                ('db_Cloth_Extra', models.TextField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='db_Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_Comment_ID', models.CharField(max_length=100)),
                ('db_Comment_Sender', models.CharField(max_length=100)),
                ('db_Comment_Text', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='db_Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_Computer_ID', models.CharField(max_length=100)),
                ('db_Computer_Store_RAM', models.TextField(max_length=255)),
                ('db_Computer_Store_ROM', models.TextField(max_length=255)),
                ('db_Computer_OS', models.TextField(max_length=255)),
                ('db_Computer_Camera', models.TextField(max_length=255)),
                ('db_Computer_Color', models.TextField(max_length=255)),
                ('db_Computer_BatteryTiming', models.TextField(max_length=255)),
                ('db_Computer_Card', models.TextField(max_length=255)),
                ('db_Computer_Charger', models.TextField(max_length=255)),
                ('db_Computer_Resolution', models.TextField(max_length=255)),
                ('db_Computer_Extra', models.TextField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('db_photo', models.ImageField(blank=True, max_length=255, upload_to='media/computer/')),
            ],
        ),
        migrations.CreateModel(
            name='db_Message_Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_Message_Sender', models.CharField(max_length=100)),
                ('db_Message_Reciever', models.CharField(max_length=100)),
                ('db_Message_Text', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='db_Mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_Mobile_ID', models.CharField(max_length=100)),
                ('db_Mobile_Store_RAM', models.TextField(max_length=255)),
                ('db_Mobile_Store_ROM', models.TextField(max_length=255)),
                ('db_Mobile_OS', models.TextField(max_length=255)),
                ('db_Mobile_Camera', models.TextField(max_length=255)),
                ('db_Mobile_Color', models.TextField(max_length=255)),
                ('db_Mobile_BatteryTiming', models.TextField(max_length=255)),
                ('db_Mobile_Card', models.TextField(max_length=255)),
                ('db_Mobile_Charger', models.TextField(max_length=255)),
                ('db_Mobile_Resolution', models.TextField(max_length=255)),
                ('db_Mobile_Extra', models.TextField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='db_Place_Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id_order', models.CharField(max_length=100)),
                ('email_user', models.EmailField(blank=True, max_length=254)),
                ('email_order', models.EmailField(blank=True, max_length=254)),
                ('fname_order', models.TextField(max_length=100)),
                ('lname_order', models.TextField(max_length=100)),
                ('company_name_order', models.TextField(max_length=100)),
                ('country_order', models.TextField(max_length=100)),
                ('street_address_order', models.TextField(max_length=100)),
                ('appartment_order', models.TextField(max_length=100)),
                ('city_address_order', models.TextField(max_length=100)),
                ('state_order', models.TextField(max_length=100)),
                ('phone_order', models.IntegerField(max_length=100)),
                ('postCode_order', models.IntegerField(max_length=100)),
                ('cash_on', models.IntegerField(max_length=100)),
                ('status_order', models.TextField(max_length=100)),
                ('price_order', models.IntegerField()),
                ('quantity_order', models.IntegerField()),
                ('card_number', models.CharField(max_length=100)),
                ('card_Holder_name', models.CharField(max_length=100)),
                ('card_expDate', models.CharField(max_length=100)),
                ('card_ccv', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='db_Product_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_Image_ID', models.CharField(max_length=100)),
                ('db_Product_photo', models.ImageField(blank=True, max_length=255, upload_to='Product/')),
                ('list1_img', models.ImageField(blank=True, max_length=255, upload_to='Product/')),
                ('list2_img', models.ImageField(blank=True, max_length=255, upload_to='Product/')),
                ('list3_img', models.ImageField(blank=True, max_length=255, upload_to='Product/')),
                ('list4_img', models.ImageField(blank=True, max_length=255, upload_to='Product/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='db_Product_Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_Order_ID', models.CharField(max_length=100)),
                ('db_Order_Email', models.EmailField(blank=True, max_length=255)),
                ('db_Order_Quantity', models.IntegerField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='db_Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_Review_ID', models.CharField(max_length=100)),
                ('db_Review_Email', models.EmailField(blank=True, max_length=254)),
                ('db_Review_Text', models.TextField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='db_Shoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_Shoes_ID', models.CharField(max_length=100)),
                ('db_Shoes_Color', models.TextField(max_length=255)),
                ('db_Shoes_GenderBase', models.TextField(max_length=255)),
                ('db_Shoes_AgeBase', models.TextField(max_length=255)),
                ('db_Shoes_Extra', models.TextField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='db_TV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_TV_ID', models.CharField(max_length=100)),
                ('db_TV_Inches', models.TextField(max_length=255)),
                ('db_TV_Color', models.TextField(max_length=255)),
                ('db_TV_Resolution', models.TextField(max_length=255)),
                ('db_TV_Extra', models.TextField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='db_Watch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_Watch_ID', models.CharField(max_length=100)),
                ('db_Watch_Color', models.TextField(max_length=255)),
                ('db_Watch_GenderBase', models.TextField(max_length=255)),
                ('db_Watch_AgeBase', models.TextField(max_length=255)),
                ('db_Watch_Extra', models.TextField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='db_Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_Wishlist_ID', models.CharField(max_length=100)),
                ('db_Wishlist_Email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
