# Generated by Django 4.2.7 on 2024-02-29 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreCommerce', '0002_db_accessories_db_cloth_db_comment_db_computer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_place_order',
            name='phone_order',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='db_place_order',
            name='postCode_order',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='db_product_order',
            name='db_Order_Quantity',
            field=models.IntegerField(),
        ),
    ]
