# Generated by Django 4.2.7 on 2024-02-29 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreCommerce', '0003_alter_db_place_order_phone_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_place_order',
            name='cash_on',
            field=models.IntegerField(),
        ),
    ]
