# Generated by Django 5.0.2 on 2024-03-04 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreCommerce', '0004_alter_db_place_order_cash_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_message_admin',
            name='db_Messsage_Email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
